# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'M-A Studee Buddee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for M-A Studee Buddee
  
  pod "YoutubePlayer-in-WKWebView", "~> 0.2.0" 
  

end
